config/routes.rb
VynilRack::Application.routes.draw do
  root to: "Sessions#new"

  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/signout" => "sessions#destroy", :as => :signout

  resources :users
  resources :recordings
  resources :identities

end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  validates_presence_of :name
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
end

# == Schema Information
#
# Table name: identities
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#

app/models/recording.rb
class Recording < ActiveRecord::Base
	belongs_to :user
	
	validates_presence_of :artist, :title 

	self.per_page = 10 # number of recorings paginated

	def self.search(search)
		if search
			where('artist LIKE ?', "%#{search}")
		else
			scoped # give all instead of searching
		end
	end

end

# == Schema Information
#
# Table name: recordings
#
#  id         :integer         not null, primary key
#  artist     :string(255)
#  title      :string(255)
#  published  :date
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  user_id    :integer
#

app/models/user.rb
class User < ActiveRecord::Base
	has_many :recordings

	def self.from_omniauth(auth)
		find_by_provider_and_uid(auth["provider"], auth["uid"]) || create_with_omniauth(auth)
	end


	def self.create_with_omniauth(auth)
		create! do |user|
			user.provider = auth["provider"]
			user.uid = auth["uid"]
			user.name = auth["info"]["name"]
		end
	end
end

# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  provider   :string(255)
#  uid        :string(255)
#  name       :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
	def new
		@identity = env['omniauth.identity']
	end
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  helper_method :sort_column, :sort_direction
  # GET /recordings
  # GET /recordings.json
  def index
    @recordings = Recording.search(params[:search]).order(sort_column + ' '  + sort_direction).paginate(:page => params[:page]) 
    #@recordings_found = Recording.where(:title.matches => "%#{params[:search]}")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recordings }
    end
  end

  # GET /recordings/1
  # GET /recordings/1.json
  def show
    @recording = Recording.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recording }
    end
  end

  # GET /recordings/new
  # GET /recordings/new.json
  def new
    @recording = Recording.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recording }
    end
  end

  # GET /recordings/1/edit
  def edit
    @recording = Recording.find(params[:id])
  end

  # POST /recordings
  # POST /recordings.json
  def create
    @recording = Recording.new(params[:recording])

    respond_to do |format|
      if @recording.save
        format.html { redirect_to @recording, notice: 'Recording was successfully created.' }
        format.json { render json: @recording, status: :created, location: @recording }
      else
        format.html { render action: "new" }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recordings/1
  # PUT /recordings/1.json
  def update
    @recording = Recording.find(params[:id])

    respond_to do |format|
      if @recording.update_attributes(params[:recording])
        format.html { redirect_to @recording, :notice => 'Recording was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to edit_recording_path(@recording), :notice => 'An error occured, Artist and Title must be entered' }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recordings/1
  # DELETE /recordings/1.json
  def destroy
    @recording = Recording.find(params[:id])
    @recording.destroy

    respond_to do |format|
      format.html { redirect_to recordings_url, :notice => @recording.artist + " " + @recording.title + " deleted" }
      format.json { head :no_content }
    end
  end

  private 
  def sort_column
    Recording.column_names.include?(params[:sort]) ? params[:sort] : "artist"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.from_omniauth(env["omniauth.auth"])
		session[:user_id] = user.id
		redirect_to root_url, notice: "Signed in!"
	end
	
	def destroy
		session[:user_id] = nil
		redirect_to root_url, notice: "Signed out!"
	end

	def failure
		redirect_to root_url, alert: "Authentification failed, please try again."
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	helper_method :sort_column, :sort_direction

  # GET /recordings/1
  # GET /recordings/1.json
  def show
    @user = User.find(params[:id])
    @recordings = @user.recordings.search(params[:search]).order(sort_column + ' '  + sort_direction).paginate(:page => params[:page]) 
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end
  
  private 
  def sort_column
    Recording.column_names.include?(params[:sort]) ? params[:sort] : "artist"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-error"
    when :alert then "alert alert-error"
    end
  end
  def sortable(column, title = nil)
  	title ||= column.titleize
  	css_class = (column == sort_column) ? "label label-info": nil  
  	direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
	link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}  	
  end
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/identities/new.html.erb
<%= form_tag "/auth/identity/register" do %>
<% if @identity && @identity.errors.any? %>
<div class="error_messages">
  <h2><%= pluralize(@identity.errors.count, "error") %> prohibited this account from being saved:</h2>
  <ul>
    <% @identity.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="well form">
<div class="controls">
  <%= label_tag :name, "Name", :class => 'control'%>
  <%= text_field_tag :name, @identity.try(:name), :class => 'control' %>
</div>
<div class="controls">
  <%= label_tag :email, "Email", :class => 'control' %>
  <%= text_field_tag :email, @identity.try(:email), :class => 'control' %>
</div>
<div class="controls">
  <%= label_tag :password, "Password", :class => 'control' %>
  <%= password_field_tag :password, nil, :class => 'control' %>
</div>
<div class="controls">
  <%= label_tag :password_confirmation, "Password confirmation",:class => 'control'%>
  <%= password_field_tag :password_confirmation, nil, :class => 'control' %>
</div>
<div class="form-actions"><%= submit_tag "Register", :class => "btn" %></div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>VynilRack</title>
	  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<%= link_to "VynilRack", root_path, :class => "brand" %>
				<div class="nav-collapse">
					<ul class="nav">
						<li><%= link_to "Browse Products", recordings_path %></li>
						<li><%= link_to "Price List" %></li>
						<li><%= link_to "Contact Us" %></li>
						<li><%= link_to "Cart" %></li>
						<li class="dropdown">
					</ul>
					<ul class="nav pull-right">
							<% if current_user %>
							<li>
									<%= link_to "Sign Out: #{current_user.name}", signout_path%>
							</li>
							<% else %>
							<li class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown" href="#">
									Sign in
									<b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									<%= render "shared/external_signin_text" %>
								</ul>
							</li>
							<% end %>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="span9">
				<%= render :partial => "shared/flash_messages", :locals => {:flash => flash} %> 
				<%= yield %>
			</div>
			<div class="span3">
				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
				consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			</div>
		</div>
	</div>

</body>
</html>

app/views/recordings/_form.html.erb
<%= form_for @recording, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Recording</legend>

    <div class="control-group">
      <%= f.label :artist, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :artist, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :title, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :published, :class => 'control-label' %>
      <div class="controls">
        <%= f.date_select :published, :class => 'date_select', :start_year => 1900 %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', recordings_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/recordings/edit.html.erb
<%= render :partial => 'form' %>

app/views/recordings/index.html.erb
<h1>Recordings</h1>

<%= form_tag recordings_path, :method => 'get' do %>
<p>
  <div class="control-group">
    <div class="well form-search">
      <%= text_field_tag :search, params[:search], :class => "input-medium search-query" %>
      <%= submit_tag "Search", :name => nil, :class => 'btn' 'btn-mini' %>
    </div>
  </div>
</p>
<% end %>

<%= render 'shared/recordings_index' %>

<%= link_to 'New', new_recording_path, :class => 'btn btn-primary' %>

app/views/recordings/new.html.erb
<%= render :partial => 'form' %>

app/views/recordings/show.html.erb
<h1>Recording</h1>

<p>
  <b>Artist</b><br>
  <%= @recording.artist %>
</p>

<p>
  <b>Title</b><br>
  <%= @recording.title %>
</p>

<p>
  <b>Published</b><br>
  <%= @recording.published %>
</p>

<div class="form-actions">
  <%= link_to 'Back', recordings_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_recording_path(@recording), :class => 'btn' %>
  <%= link_to 'Delete', recording_path(@recording), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>

app/views/shared/_external_signin.html.erb
    <li>
      <a href="/auth/twitter" class="auth_provider">
        <%= image_tag "twitter_64.png", size: "64x64", alt: "Twitter" %> 
      </a>
    </li>
    <li>
      <a href="/auth/facebook" class="auth_provider">
        <%= image_tag "facebook_64.png", size: "64x64", alt: "Facebook" %> 
      </a>
    </li>
    <li>
      <a href="/auth/google_apps" class="auth_provider">
        <%= image_tag "google_apps_64.png", size: "64x64", alt: "Google" %>
      </a>
    </li>

app/views/shared/_external_signin_text.html.erb
    <li>
      <a href="/auth/twitter" class="auth_provider">
        Twitter
      </a>
    </li>
    <li>
      <a href="/auth/facebook" class="auth_provider">
        Facebook
      </a>
    </li>
    <li>
      <a href="/auth/google_apps" class="auth_provider">
        Google
      </a>
    </li>
    <li>
      <a href="/identities/new" class="auth_provider">
        Create an account
      </a>
    </li>

app/views/shared/_flash_messages.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> fade in">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/shared/_recordings_index.html.erb
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th><%= sortable "artist" %></th>
      <th><%= sortable "title" %></th>
      <th><%= sortable "published" %></th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @recordings.each do |recording| %>
    <tr>
      <td><%= link_to recording.artist, recording_path(recording) %></td>
      <td><%= recording.title %></td>
      <td><%= recording.published %></td>
      <td id ="recording_<%= recording.id %>" >
        <%= link_to 'Edit', edit_recording_path(recording), :class => 'btn btn-mini' %>
        <%= link_to 'Destroy', recording_path(recording), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger'%>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @recordings %>

app/views/users/show.html.erb
<h1>Recordings</h1>

<%= form_tag recordings_path, :method => 'get' do %>
<p>
  <div class="control-group">
    <div class="well form-search">
      <%= text_field_tag :search, params[:search], :class => "input-medium search-query" %>
      <%= submit_tag "Search", :name => nil, :class => 'btn' 'btn-mini' %>
    </div>
  </div>
</p>
<% end %>

<div id="recordings">
  <%= render 'shared/recordings_index' %>
</div>

<%= link_to 'New', new_recording_path, :class => 'btn btn-primary' %>